export const ALL_PRODUCTS_REQUEST ="ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS="ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL="ALL_PRODUCTS_FAIL"

export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL="PRODUCT_DETAILS_FAIL"

//CONSTANTES PARA REGISTRAR PRODUCTOS
export const REGISTER_PRODUCT_REQUEST="REGISTER_PRODUCT_REQUEST"
export const REGISTER_PRODUCT_SUCCESS="REGISTER_PRODUCT_SUCCESS"
export const REGISTER_PRODUCT_FAIL="REGISTER_PRODUCT_FAIL"

export const CLEAR_ERRORS="CLEAR_ERRORS"
